import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import React, { Suspense } from "react";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import ReduxProvider from "@/app/components/ReduxProvider";
import Preloader from "@/app/components/Preloader";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";
import { NextAuthProvider } from "@/app/components/NextAuthProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/lib/authOptions";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    const session = await getServerSession(authOptions);

    return (
        <NextAuthProvider session={session}>
            <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <Navbar/>
            <main className='min-h-screen max-w-screen-2xl mx-auto px-4 py-6 font-primary'>
                <Suspense fallback={<Preloader/>}>
                    <ReduxProvider>
                        {children}
                    </ReduxProvider>
                </Suspense>
            </main>
            <ToastContainer/>
            <Footer/>
            </body>
            </html>
        </NextAuthProvider>
    );
}
